### ISSUE TITLE
JMH JSON generation slow for big result sets

### ISSUE THREAD

**Issue by japgolly** [japgolly/scalajs-benchmark#80]

**Comment by plokhotnyuk** [comment]
Do you know the root cause of the slowdown? 

Is it possible to get some hints from profilers in browsers?

Would you consider to use jsoniter-scala for serialization of JSON? 

From first measurements with Node.js it has shown [some promising results](https://gitter.im/plokhotnyuk/jsoniter-scala?at=5eb5823c3d58de7a380278f0). 

Moreover, it can serialize immediately into `java.io.OutputStream` without intermediate representations like JSON ASTs or strings. 

Also, it emits shorter floats and doubles without loosing of information, but it can cost more CPU cycles, so I'm not 100% sure about this idea, yet. :)

**Comment by japgolly** [comment]
Hey @plokhotnyuk , thanks for the idea but it wasn't the JSON generation itself. It was way I was recording stats internally which I've just fixed in #84
