### ISSUE TITLE
Saving batch results to one file wanted

### ISSUE THREAD

**Issue by plokhotnyuk** [japgolly/scalajs-benchmark#96]
The Safari browser asks to allow downloading for each file when the page is opened locally.

Automatic allowing of downloads works only for websites in it.

It is not a problem to press the `Allow` button for each suite and then merge results by a command like `jq -s '[.[][]]' sjsbm-*.json > safari.json`.

But it starts to be unpractical when there are a lot of suites because the browser blocks execution of benchmarks until the `Allow` button will be pressed.

BTW: the Brave browser doesn't block running of benchmarks if the multi-file download was allowed but it asks for saving of each file.

**Comment by japgolly** [comment]
FYI I'm using chrome and it happily saves multiple files on demand. I'm on Linux, I don't have OSX to test Safari.

But yeah, we can add an option to save a single file at the end. I'd like an option to save a zip with each suite's json in it, rather than consolidating json files. Is that ok with you @plokhotnyuk ?

**Comment by plokhotnyuk** [comment]
Yep, zip of files could be more practical.

**Comment by plokhotnyuk** [comment]
Just realized that last versions the Chrome browser stop multi-file downloading on about 50th file and re-ask confirmation for downloading of multiple files.
